name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Build
      run: |
        npm install
        # npx webpack
        npx esbuild main.ts --bundle --outfile=main.js --format=esm
        pwd
        ls -al
    - name: remove gerbages
      run: |
        rm -r node_modules
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        path: .
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
